### ISSUE TITLE
Crafting Recipe Doesn't Work

### ISSUE THREAD

**Issue by Rosesofink** [Fusion-Flux/Origins-Umbrellas#1]
The umbrella currently isn't able to be crafted without modification to the mod. The issue is that the recipe folder is capitalized where it needs to be all lower case.

Issue:
![Issue](https://user-images.githubusercontent.com/80267978/110334520-dd808c80-7ff0-11eb-8e8c-2fbcc659e757.JPG)
Solution:
![Fix](https://user-images.githubusercontent.com/80267978/110334550-e5d8c780-7ff0-11eb-9f22-7bd17e455741.JPG)
(I made this edit using WinRAR, the folders with "..." do not exist. I've tested it and it does work once the folder is all lower case).

**Comment by Fusion-Flux** [comment]
will fix!
